ips_symfony_project_homepage:
    path:     /
    defaults: { _controller: IPSSymfonyProjectBundle:Default:index }

go_to_home:
    path:     /home
    defaults: { _controller: IPSSymfonyProjectBundle:Default:home }

create_new_project:
    path: /create/project
    defaults: { _controller: IPSSymfonyProjectBundle:Default:newproject }

submit_new_project:
    path: /save/project
    defaults: { _controller: IPSSymfonyProjectBundle:Default:saveproject }

show_projects:
    path: /projects
    defaults: { _controller: IPSSymfonyProjectBundle:Default:showprojects }

edit_projects:
    path: /edit/projects
    defaults: { _controller: IPSSymfonyProjectBundle:Default:editprojects }

edit_project:
    path: /edit/project/{id}
    defaults: { _controller: IPSSymfonyProjectBundle:Default:editproject }

update_project:
    path: /update/project/{id}
    defaults: { _controller: IPSSymfonyProjectBundle:Default:updateproject }

delete_project:
    path: /delete/project/{id}
    defaults: { _controller: IPSSymfonyProjectBundle:Default:deleteproject }

create_new_section:
    path: /add/section/{proj}
    defaults: { _controller: IPSSymfonyProjectBundle:Default:addsection }

submit_new_section:
    path: /save/section
    defaults: { _controller: IPSSymfonyProjectBundle:Default:savesection }

show_project:
    path: /show/project/{id}
    defaults: { _controller: IPSSymfonyProjectBundle:Default:showproject }

create_new_task:
    path: /add/task/{sect}
    defaults: { _controller: IPSSymfonyProjectBundle:Default:addtask }

submit_new_task:
    path: /save/task
    defaults: { _controller: IPSSymfonyProjectBundle:Default:savetask }
# a faire
show_task:
    path: /show/task/{id}
    defaults: { _controller: IPSSymfonyProjectBundle:Default:showtask }

show_section:
    path: /show/section/{id}
    defaults: { _controller: IPSSymfonyProjectBundle:Default:showsection }