ips_symfony_project:
    resource: "@IPSSymfonyProjectBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: '@AppBundle/Controller/'
    type: annotation

login:
    path: /login
    defaults:
        _controller: ResearchLabUserBundle:Security:login

login_check:
    path: /login_check

logout:
    path: /logout